blank_issues_enabled: true
contact_links:
  - name: Issue with MASA Stack Documentation
    url:  https://github.com/masastack/MASA.Docs/issues/new/choose
    about: Please open issues relating to MASA Stack in masastack/MASA.Docs.