global using MASA.BuildingBlocks.Configuration;
global using MASA.Contrib.BasicAbility.Dcc.Internal;
global using MASA.Contrib.BasicAbility.Dcc.Internal.Model;
global using MASA.Contrib.BasicAbility.Dcc.Internal.Parser;
global using MASA.Contrib.BasicAbility.Dcc.Options;
global using MASA.Utils.Caching.Core.DependencyInjection;
global using MASA.Utils.Caching.Core.Models;
global using MASA.Utils.Caching.DistributedMemory.DependencyInjection;
global using MASA.Utils.Caching.DistributedMemory.Interfaces;
global using MASA.Utils.Caching.Redis.DependencyInjection;
global using MASA.Utils.Caching.Redis.Extensions;
global using MASA.Utils.Caching.Redis.Models;
global using MASA.Utils.Caller.Core;
global using MASA.Utils.Caller.HttpClient;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Dynamic;
global using System.Text.Json;
global using static MASA.Contrib.BasicAbility.Dcc.Internal.Constants;

