global using MASA.BuildingBlocks.Dispatcher.IntegrationEvents;
global using MASA.BuildingBlocks.Dispatcher.IntegrationEvents.Logs;
global using MASA.Contrib.Dispatcher.IntegrationEvents.Dapr;
global using MASA.Contrib.Dispatcher.IntegrationEvents.EventLogs.EF.Tests.Events;
global using MASA.Utils.Data.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System.Data.Common;
